version: "2"
services:
  nginx:
    image: nginx:alpine
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./environment/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80

  magento:
    image: vitormarcelino/magento2-environment:8.1
    restart: always
    working_dir: /var/www/html
    expose:
      - 9000
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./.docker/dbdata:/var/lib/mysql:delegated

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  data: